In [1]:
import numpy as np

# 2-Dimensional Array


In [2]:
a = np.array([[[1], [2], [3]], [[4], [5], [6]]])

In [3]:
print(a)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


# Get Shape

In [4]:
a.shape

(2, 3, 1)

# Get dimension

In [5]:
a.ndim

3

# Get Data Type

In [6]:
a.dtype

dtype('int32')

In [7]:
b = np.zeros((2, 3)) 

In [8]:
b.shape

(2, 3)

In [9]:
b.reshape((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
b = np.zeros((5, 5), dtype = "int32")

In [11]:
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8])
c = c.reshape((2, 4))

In [13]:
c.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[5, 6], [6, 7], [1, 2]])
d.shape

(3, 2)

In [15]:
np.dot(c, d)

array([[20, 26],
       [56, 71]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d

array([[5, 6],
       [6, 7],
       [1, 2]])

In [23]:
b[1:4, 1:4] = np.ones((3, 3))

In [19]:
b

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [20]:
b[2, 2] = np.full((1, 1), 9)

In [21]:
b

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 9, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])