In [1]:
import numpy as np

# Random Module

In [2]:
a = np.random.randint(60, 100, 10)
a

array([90, 98, 89, 79, 65, 61, 82, 99, 93, 69])

# Random Module with shape

In [3]:
a = np.random.randint(60, 100, (5, 5))

In [4]:
a

array([[82, 81, 60, 69, 76],
       [74, 81, 66, 84, 62],
       [92, 96, 78, 63, 86],
       [87, 68, 70, 83, 66],
       [66, 93, 82, 85, 85]])

# Doing operations on the Random Value Array(a)

In [5]:
print("Maximum: ")
print(np.max(a)) # Finding maximum value in the array
print("Minimum: ")
print(np.min(a)) # Finding minimum value in the array

Maximum: 
96
Minimum: 
60


In [6]:
print("Index of Maximum Number: ")
print(np.argmax(a)) # Finding index of maximum value in the array
print("Index of Minimum Number: ")
print(np.argmin(a)) # Finding index of maximum value in the array

Index of Maximum Number: 
11
Index of Minimum Number: 
2


In [7]:
print("Finding the unique elements in an array: ")
print(np.unique(a, return_counts = True))

Finding the unique elements in an array: 
(array([60, 62, 63, 66, 68, 69, 70, 74, 76, 78, 81, 82, 83, 84, 85, 86, 87,
       92, 93, 96]), array([1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1],
      dtype=int64))


# Slicing Excercise

In [8]:
print(a[0, 2])

60


In [9]:
print(a[:, 3])

[69 84 63 83 85]


In [10]:
print(a[:2, -1])

[76 62]


# Identity Matrix

In [16]:
print(np.eye(5, dtype = "int8"))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Finding Evenly Spaced Numbers

In [12]:
print(np.linspace(1, 10, 5))

[ 1.    3.25  5.5   7.75 10.  ]
