In [2]:
import numpy as np

# Arithmetic Section

## Addition

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [4]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
a + b

array([[ 6,  8],
       [10, 12]])

### Or

In [6]:
print(np.add(a, b))

[[ 6  8]
 [10 12]]


## Subtraction

In [7]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [8]:
print(np.subtract(b, a))

[[4 4]
 [4 4]]


## Multiplication

In [9]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [10]:
print(a * b)

[[ 5 12]
 [21 32]]


### Or

In [11]:
print(np.multiply(a, b))

[[ 5 12]
 [21 32]]


## Division

In [12]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [13]:
print(np.divide(a, b))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Or

In [14]:
print(a / b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## Square Root

In [15]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [16]:
print("A:")
print(np.sqrt(a))

A:
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
print("B:")
print(np.sqrt(b))

B:
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


## Sum of all elements inside an Array

In [18]:
print(b)

[[5 6]
 [7 8]]


In [19]:
print(np.sum(b))

26


# Arange

In [20]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [30]:
print(np.arange(10) + 1)

[ 1  2  3  4  5  6  7  8  9 10]


# Shuffling of Elements

In [22]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.random.shuffle(c)
print(c)

[6 1 3 8 2 7 5 4]


# Statistical Operations

## Finding the Mean

In [24]:
print(np.mean(c))

4.5


## Finding the Median

In [25]:
print(np.median(c))

4.5


## Finding the variance

In [26]:
print(np.var(c))

5.25


In [27]:
((2.5 ** 2) + (1.5 ** 2) + (3.5 ** 2) + (3.5 ** 2) + (0.5 ** 2) + (1.5 ** 2) + (2.5 ** 2) + (0.5 ** 2)) / 8

5.25

## Finding the Standard Deviation

In [28]:
print(round(np.std(c), 2))

2.29


In [29]:
np.sqrt(5.25)

2.29128784747792