In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('mnist_train.csv')

In [4]:
df.head(30)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0       5    0    0    0    0    0    0    0    0    0  ...      0      0   
1       0    0    0    0    0    0    0    0    0    0  ...      0      0   
2       4    0    0    0    0    0    0    0    0    0  ...      0      0   
3       1    0    0    0    0    0    0    0    0    0  ...      0      0   
4       9    0    0    0    0    0    0    0    0    0  ...      0      0   
5       2    0    0    0    0    0    0    0    0    0  ...      0      0   
6       1    0    0    0    0    0    0    0    0    0  ...      0      0   
7       3    0    0    0    0    0    0    0    0    0  ...      0      0   
8       1    0    0    0    0    0    0    0    0    0  ...      0      0   
9       4    0    0    0    0    0    0    0    0    0  ...      0      0   
10      3    0    0    0    0    0    0    0    0    0  ...      0      0   
11      5    0    0    0    0    0    0    0    0    0  ...      0      0   
12      3    0    0    0    0    0    0    0    0    0  ...      0      0   
13      6    0    0    0    0    0    0    0    0    0  ...      0      0   
14      1    0    0    0    0    0    0    0    0    0  ...      0      0   
15      7    0    0    0    0    0    0    0    0    0  ...      0      0   
16      2    0    0    0    0    0    0    0    0    0  ...      0      0   
17      8    0    0    0    0    0    0    0    0    0  ...      0      0   
18      6    0    0    0    0    0    0    0    0    0  ...      0      0   
19      9    0    0    0    0    0    0    0    0    0  ...      0      0   
20      4    0    0    0    0    0    0    0    0    0  ...      0      0   
21      0    0    0    0    0    0    0    0    0    0  ...      0      0   
22      9    0    0    0    0    0    0    0    0    0  ...      0      0   
23      1    0    0    0    0    0    0    0    0    0  ...      0      0   
24      1    0    0    0    0    0    0    0    0    0  ...      0      0   
25      2    0    0    0    0    0    0    0    0    0  ...      0      0   
26      4    0    0    0    0    0    0    0    0    0  ...      0      0   
27      3    0    0    0    0    0    0    0    0    0  ...      0      0   
28      2    0    0    0    0    0    0    0    0    0  ...      0      0   
29      7    0    0    0    0    0    0    0    0    0  ...      0      0   

    28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0       0      0      0      0      0      0      0      0  
1       0      0      0      0      0      0      0      0  
2       0      0      0      0      0      0      0      0  
3       0      0      0      0      0      0      0      0  
4       0      0      0      0      0      0      0      0  
5       0      0      0      0      0      0      0      0  
6       0      0      0      0      0      0      0      0  
7       0      0      0      0      0      0      0      0  
8       0      0      0      0      0      0      0      0  
9       0      0      0      0      0      0      0      0  
10      0      0      0      0      0      0      0      0  
11      0      0      0      0      0      0      0      0  
12      0      0      0      0      0      0      0      0  
13      0      0      0      0      0      0      0      0  
14      0      0      0      0      0      0      0      0  
15      0      0      0      0      0      0      0      0  
16      0      0      0      0      0      0      0      0  
17      0      0      0      0      0      0      0      0  
18      0      0      0      0      0      0      0      0  
19      0      0      0      0      0      0      0      0  
20      0      0      0      0      0      0      0      0  
21      0      0      0      0      0      0      0      0  
22      0      0      0      0      0      0      0      0  
23      0      0      0      0      0      0      0      0  
24      0      0      0      0      0      0      0      0  
25      0      0      0      0

In [5]:
df.shape

(60000, 785)

In [6]:
df_arr = df.values

In [7]:
print(df_arr)

[[5 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [4 0 0 ... 0 0 0]
 ...
 [5 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [8 0 0 ... 0 0 0]]


In [8]:
X = df_arr[:, 1:]
y = df_arr[:, 0]
print(X)
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[5 0 4 ... 5 6 8]


# Plot an image in matplotlib

In [9]:
plt.imshow(X[26].reshape(2, 2), cmap = 'gray')

ValueError: cannot reshape array of size 784 into shape (2,2)

In [ ]:
df.iloc[26:27, 0:1]