In [14]:
import numpy as np

In [18]:
A = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [44]:
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]
hello world


In [22]:
# Get Dimensions

print("Array A: ")
print("")
print(A.ndim)
print("")
print("-----------------------------------------------")
print("")
print("Array B: ")
print("")
print(B.ndim)

Array A: 

1

-----------------------------------------------

Array B: 

2


In [23]:
# Get Shape

print("Array A: ")
print("")
print(A.shape)
print("")
print("-----------------------------------------------")
print("")
print("Array B: ")
print("")
print(B.shape)

Array A: 

(4,)

-----------------------------------------------

Array B: 

(2, 4)


In [24]:
# Get Size

print("Array A: ")
print("")
print(A.itemsize)
print("")
print("-----------------------------------------------")
print("")
print("Array B: ")
print("")
print(B.itemsize)

Array A: 

4

-----------------------------------------------

Array B: 

4


In [45]:
# Get Total Size

print("Array A: ")
print("")
print(A.nbytes)
print("")
print("-----------------------------------------------")
print("")
print("Array B: ")
print("")
print(B.nbytes)

Array A: 

16

-----------------------------------------------

Array B: 

32
