In [1]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [5]:
# Get specific Element [row, column]

print(a[1, 4])

13


In [6]:
# Get Specific Row

print(a[0, :])

[1 2 3 4 5 6 7 8]


In [7]:
# Get specific Column

print(a[:, 2])

[ 3 11]


In [12]:
# Get elements between specified indexes [row, startindex:endindex:stepsize]

print(a[0, 4:8:1])

[5 6 7 8]


In [ ]:
hk;q;--# Change a specific element ([specific element] = [value])

print(a[0, 7])