In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
# Copying Arrays

b = a.copy()

print(b)

[1 2 3 4]


In [6]:
b[0] = 100

print(b)

[100   2   3   4]


In [7]:
# Mathematics

a + 2    # Adds 2 to each element

array([3, 4, 5, 6])

In [8]:
a - 2    # Subtracts 2 from each element

array([-1,  0,  1,  2])

In [ ]:
# And so on