In [10]:
import numpy as np

In [19]:
a = np.array([1, 2, 3], dtype = 'int8')
a

array([1, 2, 3], dtype=int8)

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
print(a.shape)

(2, 3)


In [18]:
a = np.array([1.0, 2.0, 2.3])
print(a)

[1.  2.  2.3]


In [22]:
print(a.size)

6
